name: Job board CI/CD pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  test_push:
    env:
      CI: false
      MONGO_URI: ${{ secrets.MONGO_URI }}
      CRYPTO_HASH_ALGORITHM: ${{ secrets.CRYPTO_HASH_ALGORITHM }}
      CRYPTO_HASH_ENCODING: ${{ secrets.CRYPTO_HASH_ENCODING }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      COOKIE_PARSER_SECRET: ${{ secrets.COOKIE_PARSER_SECRET }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use NodeJs version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install all dependencies
        run: npm install

      # Skip building for now
      # - name: Create an optimised version of the front-end
      #   run: npm run build --prefix client

      - name: Test the app
        run: npm test
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # - name: Build docker image and push it to DockerHub
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     build-args: |
      #       "MONGO_URI: ${{ secrets.MONGO_URI }}"
      #       "CRYPTO_HASH_ALGORITHM: ${{ secrets.CRYPTO_HASH_ALGORITHM }}"
      #       "CRYPTO_HASH_ENCODING: ${{ secrets.CRYPTO_HASH_ENCODING }}"
      #       "JWT_SECRET: ${{ secrets.JWT_SECRET }}"
      #       "CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}"
      #       "STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}"
      #       "CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}"
      #       "CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}"
      #       "COOKIE_PARSER_SECRET: ${{ secrets.COOKIE_PARSER_SECRET }}"
      #       "SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}"
      #     push: true
      #     tags: eusebiuu/job-board
